markdown: rdiscount
permalink: /:year/:month-:day-:title.html
destination: _site
url: veekxt.github.io
name: Veekxt
author: Veekxt
email: veekxt@gmail.com
duoshuo: veekxt
github: veekxt
gitcafe: veekxt
highlighter: pygments
safe: false
paginate: 30
truncate: false
tkurl: veekxt.com
auto: true
baseurl:  